version: '2.1'

services:

  app:
    image: ${DOCKER_IMAGE}
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    build:
      context: .
      args:
        - GOLANG_VERSION

  nats:
    image: nats:2.10.5
    ports:
      - ${TEST_NATS_PORT}:4222

  pg:
    image: postgres:15.2-alpine
    ports:
      - ${TEST_PG_PORT}:5432
    environment:
      - POSTGRES_USER=mqbridge
      - POSTGRES_PASSWORD=${TEST_PG_PASS}
      - POSTGRES_DB=mqbridge_test
    volumes:
      - ./var/data:/var/lib/postgresql/data
    stop_signal: SIGINT
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-U", "postgres"]
      interval: 2s
      timeout: 3s
      retries: 3
