version: '2.1'

services:

  app:
    image: ${DC_IMAGE}
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    build:
      context: .
      args:
        - GOLANG_VERSION

  nats:
    image: nats-streaming:0.20.0-alpine3.12
    ports:
      - ${TEST_NATS_PORT}:4222

  pg:
    image: postgres:13.1-alpine
    ports:
      - ${TEST_PG_PORT}:5432
    environment:
      - POSTGRES_USER=mqbridge
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=mqbridge_test
    stop_signal: SIGINT
