version: '2.1'

services:

  app:
    image: ${DC_IMAGE}
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    build:
      context: .
      args:
        - GOLANG_VERSION
