version: '2.1'

services:


  nats:
    image: ${NATS_IMAGE}:${NATS_IMAGE_VER}
    networks:
      - lan

  mqbr1:
    image: ${DC_IMAGE}
    command:
      --log_level debug
      --in ${DSN}
      --out ${DSN_NATS}
      --bridge ${BR_IN},${BR_NATS}
    networks:
      - lan

  mqbr2:
    image: ${DC_IMAGE}
    command:
      --log_level debug
      --in ${DSN_NATS}
      --out ${DSN}
      --bridge ${BR_NATS},${BR_OUT}
    networks:
      - lan

networks:
  lan:
    external:
      name: ${DCAPE_NET}


