version: '2.1'

services:

  mqbr:
    image: ${DC_IMAGE}
    command:
      --log_level debug
      --in ${DSN}
      --out ${DSN}
      --bridge ${BR_IN},${BR_OUT}
    networks:
      - lan

networks:
  lan:
    external:
      name: ${DCAPE_NET}

